#!/usr/bin/env python3
"""
Monitor Home Assistant Core's ha-frontend pin and analyze pin bumps for
impact on the ha-lcars theme.

Auto mode (no args) follows the frontend version currently pinned by the
latest home-assistant/core release (stable or pre-release). When that pin
differs from the last analyzed pin (`.state.json:last_analyzed_pin`) it
emits one report keyed to the Core release tag that carried the bump.
Every intermediate ha-frontend release in the range — including tags Core
skipped — is enumerated in the report's release-notes section.

Usage:
    python3 py/release_impact.py                   # scheduled: watch the Core pin
    python3 py/release_impact.py --latest-beta     # pipeline: latest Core pre-release pin (no state update)
    python3 py/release_impact.py --since 20260101.0  # force a base frontend tag (backfill)
    python3 py/release_impact.py --tag 20260527.2    # single-frontend-release analysis (backfill)
    python3 py/release_impact.py --list             # list recent frontend releases and exit

Requires:
    ANTHROPIC_API_KEY environment variable
    GitHub CLI (gh) authenticated, or GITHUB_TOKEN environment variable

State is stored in docs/release-impact/.state.json:
    last_analyzed_pin     — frontend version last analyzed
    last_analyzed_core_tag — Core release that carried that pin
    last_run              — ISO 8601 UTC
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

import requests

REPO_ROOT = Path(__file__).parent.parent
FRONTEND_REPO = "home-assistant/frontend"
OUTPUT_DIR = REPO_ROOT / "docs" / "release-impact"
STATE_FILE = OUTPUT_DIR / ".state.json"
SRC_DIR = REPO_ROOT / "src"

# Files in ha-frontend with high relevance to the LCARS theme
# (CSS vars, card/panel layout, lovelace components, sidebar/header)
RELEVANT_PATH_PREFIXES = (
    "src/panels/lovelace/",
    "src/panels/config/dashboard/",
    "src/components/ha-card",
    "src/components/ha-icon",
    "src/components/ha-chip",
    "src/components/ha-top-app-bar",
    "src/components/ha-sidebar",
    "src/components/ha-navigation-list",
    "src/components/ha-entity",
    "src/components/ha-state",
    "src/components/ha-button",
    "src/components/ha-slider",
    "src/layouts/",
    "src/resources/",
    "src/styles/",
    "hassio/src/",
)
# Skip files that are very unlikely to touch styling
SKIP_SUFFIXES = (
    ".json",
    ".md",
    "test.ts",
    ".spec.ts",
    "_test.ts",
    "translations/",
    "localize/",
)

MAX_PATCH_CHARS = 800     # per file
MAX_DIFF_FILES = 60       # total files to send to Claude

RELEASE_FILE_PREAMBLE = """\
<!-- AUTO-GENERATED by py/release_impact.py — DO NOT EDIT MANUALLY -->
<!--
  This file was generated by the ha-frontend release impact analyzer.
  It summarizes changes in an ha-frontend release that may affect the ha-lcars theme.

  DEVELOPER INSTRUCTIONS:
    1. Review each item below. Items in the HIGH IMPACT section require attention first.
    2. For each issue you resolve (variable renamed, selector changed, etc.), mark it done
       by adding a ✅ to the start of that bullet point.
    3. When ALL items are resolved, DELETE THIS FILE from the repository.

  Do not merge this file into main — it is a working document only.
-->
"""


# ──────────────────────────────────────────────────────────────────────────────
# GitHub helpers
# ──────────────────────────────────────────────────────────────────────────────

def _github_token() -> str:
    tok = os.environ.get("GITHUB_TOKEN", "")
    if not tok:
        try:
            tok = subprocess.check_output(["gh", "auth", "token"], text=True).strip()
        except Exception:
            pass
    if not tok:
        sys.exit("ERROR: No GitHub token found. Set GITHUB_TOKEN or authenticate via `gh auth login`.")
    return tok


def gh_get(path: str, token: str, params: dict | None = None) -> dict | list:
    url = f"https://api.github.com/{path.lstrip('/')}"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    resp = requests.get(url, headers=headers, params=params, timeout=30)
    resp.raise_for_status()
    return resp.json()


def get_releases(token: str, per_page: int = 50) -> list[dict]:
    return gh_get(f"repos/{FRONTEND_REPO}/releases", token, params={"per_page": per_page})  # type: ignore[return-value]


def get_compare(token: str, base: str, head: str) -> dict:
    return gh_get(f"repos/{FRONTEND_REPO}/compare/{base}...{head}", token)  # type: ignore[return-value]


def get_release_by_tag(token: str, tag: str) -> dict:
    return gh_get(f"repos/{FRONTEND_REPO}/releases/tags/{tag}", token)  # type: ignore[return-value]


# ──────────────────────────────────────────────────────────────────────────────
# home-assistant/core lookup (pin tracking)
# ──────────────────────────────────────────────────────────────────────────────

CORE_REPO = "home-assistant/core"


def get_core_releases(token: str, per_page: int = 50) -> list[dict]:
    """Fetch home-assistant/core releases (both stable and pre-release)."""
    return gh_get(f"repos/{CORE_REPO}/releases", token, params={"per_page": per_page})  # type: ignore[return-value]


def get_core_release_manifest_pin(core_tag: str) -> str | None:
    """Return the ha-frontend version pinned by Core at *core_tag*.

    Reads homeassistant/components/frontend/manifest.json via the raw file
    endpoint. Public repo — no auth required. Returns None if the manifest is
    missing, malformed, or has no frontend requirement.
    """
    url = (
        f"https://raw.githubusercontent.com/{CORE_REPO}/{core_tag}"
        f"/homeassistant/components/frontend/manifest.json"
    )
    try:
        resp = requests.get(url, timeout=20)
        if resp.status_code != 200:
            return None
        manifest = resp.json()
    except (requests.RequestException, ValueError):
        return None
    for req in manifest.get("requirements") or []:
        if isinstance(req, str) and req.startswith("home-assistant-frontend=="):
            return req.split("==", 1)[1].strip()
    return None


_CORE_TAG_RE = re.compile(r"^(\d{4})\.(\d+)\.(\d+)(?:b(\d+))?$")


def core_tag_sort_key(tag: str) -> tuple:
    """Sort Core tags (YYYY.M.PATCH[bN]).

    Betas sort before the same-version stable: 2026.6.0b3 < 2026.6.0.
    """
    m = _CORE_TAG_RE.match(tag or "")
    if not m:
        return (0, 0, 0, 1, 0)
    year, month, patch, beta = m.groups()
    is_stable = 1 if beta is None else 0
    return (int(year), int(month), int(patch), is_stable, int(beta or 0))


def resolve_latest_pinning_release(
    core_releases: list[dict],
    prerelease_ok: bool = True,
) -> tuple[dict | None, str | None]:
    """Walk Core releases newest-first; return (release, frontend_pin) for the
    first one that actually pins a frontend version.

    Skips releases whose manifest is unavailable. When *prerelease_ok* is False,
    also skips pre-releases (so callers can find the last stable pin).
    """
    sorted_releases = sorted(
        core_releases,
        key=lambda r: core_tag_sort_key(r["tag_name"]),
        reverse=True,
    )
    for r in sorted_releases:
        if not prerelease_ok and r.get("prerelease"):
            continue
        pin = get_core_release_manifest_pin(r["tag_name"])
        if pin:
            return r, pin
    return None, None


def intermediate_frontend_releases(
    frontend_releases: list[dict],
    base_pin: str,
    head_pin: str,
) -> list[dict]:
    """Return every ha-frontend release strictly newer than *base_pin* up to and
    including *head_pin*, sorted oldest-first. Handles the case where base > head
    (a pin was reverted) by swapping ends.
    """
    lo = tag_sort_key(base_pin) if base_pin else (0, 0)
    hi = tag_sort_key(head_pin)
    if lo > hi:
        lo, hi = hi, lo
    return sorted(
        [r for r in frontend_releases if lo < tag_sort_key(r["tag_name"]) <= hi],
        key=lambda r: tag_sort_key(r["tag_name"]),
    )


# ──────────────────────────────────────────────────────────────────────────────
# State management
# ──────────────────────────────────────────────────────────────────────────────

def load_state() -> dict:
    """Load state and migrate legacy keys.

    Legacy schema (pre pin-tracking): `last_processed_tag: <frontend_tag>`.
    New schema: `last_analyzed_pin`, `last_analyzed_core_tag`.
    """
    if not STATE_FILE.exists():
        return {}
    state = json.loads(STATE_FILE.read_text())
    # One-shot migration: adopt any legacy last_processed_tag as the current pin.
    if state.get("last_processed_tag") and not state.get("last_analyzed_pin"):
        state["last_analyzed_pin"] = state.pop("last_processed_tag")
        state["state_migrated_from_last_processed_tag"] = True
    return state


def save_state(state: dict) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2))


# ──────────────────────────────────────────────────────────────────────────────
# LCARS theme context
# ──────────────────────────────────────────────────────────────────────────────

def load_lcars_context() -> str:
    """Return a condensed text summary of the LCARS theme for Claude context."""
    parts: list[str] = []

    defaults_path = SRC_DIR / "defaults.yaml"
    if defaults_path.exists():
        parts.append("=== ha-lcars/src/defaults.yaml (CSS variable definitions) ===")
        parts.append(defaults_path.read_text())

    preamble_path = SRC_DIR / "preamble.yaml"
    if preamble_path.exists():
        parts.append("=== ha-lcars/src/preamble.yaml (card-mod/UIX CSS injection rules) ===")
        parts.append(preamble_path.read_text())

    return "\n\n".join(parts)


# ──────────────────────────────────────────────────────────────────────────────
# Diff filtering
# ──────────────────────────────────────────────────────────────────────────────

def is_relevant(filename: str) -> bool:
    for suffix in SKIP_SUFFIXES:
        if suffix in filename:
            return False
    for prefix in RELEVANT_PATH_PREFIXES:
        if filename.startswith(prefix):
            return True
    # Also catch any file that explicitly touches CSS custom properties
    return False


def format_diff_for_prompt(compare: dict) -> tuple[str, list[str]]:
    """Return (formatted diff text, list of all changed filenames)."""
    all_files = compare.get("files", [])
    all_names = [f["filename"] for f in all_files]

    relevant = [f for f in all_files if is_relevant(f["filename"])]
    other = [f for f in all_files if not is_relevant(f["filename"])]

    lines: list[str] = []

    lines.append(f"Total files changed: {len(all_files)}")
    lines.append(f"Relevant to LCARS styling (included below): {len(relevant)}")
    lines.append(f"Other files (names only): {len(other)}")
    if other:
        lines.append("  " + ", ".join(f["filename"] for f in other[:40]))
        if len(other) > 40:
            lines.append(f"  ... and {len(other) - 40} more")
    lines.append("")

    included = relevant[:MAX_DIFF_FILES]
    for f in included:
        lines.append(f"--- {f['filename']}  (+{f['additions']} -{f['deletions']}) ---")
        patch = f.get("patch", "")
        if patch:
            if len(patch) > MAX_PATCH_CHARS:
                patch = patch[:MAX_PATCH_CHARS] + f"\n... [truncated, {len(patch) - MAX_PATCH_CHARS} more chars]"
            lines.append(patch)
        else:
            lines.append("[binary or empty diff]")
        lines.append("")

    return "\n".join(lines), all_names


# ──────────────────────────────────────────────────────────────────────────────
# Claude analysis
# ──────────────────────────────────────────────────────────────────────────────

def analyze_with_claude(
    release: dict,
    diff_text: str,
    lcars_context: str,
    pipeline_releases: list[dict] | None = None,
    base_tag: str | None = None,
    core_release: dict | None = None,
    pin_mode: str | None = None,
) -> str:
    """Call Claude Sonnet and return the raw markdown analysis.

    Three prompt framings:

    * `pipeline_releases` is set and `pin_mode is None` → the legacy pre-release
      pipeline framing (see PR #220): "one report covers this batch of beta
      frontend releases from the last stable frontend to the current head."
    * `pin_mode == "shipped"` → Core just pinned a new frontend on a released
      Core tag; the report covers `base_tag → release.tag_name` on the frontend
      repo, with intermediate frontend release notes attached. Filename lands on
      the Core tag that carried the pin.
    * `pin_mode == "pipeline"` → same, but for a Core pre-release; the base is
      whatever the last stable Core pinned. Used by --latest-beta.

    In both pin_mode framings, *core_release* is the Core release dict that
    bumped the pin, and *base_tag* is the previous frontend pin (before the
    bump).
    """
    import anthropic

    client = anthropic.Anthropic()

    tag = release["tag_name"]
    published = release["published_at"]
    body = release.get("body") or "(no release notes)"
    is_pre = release.get("prerelease", False)
    release_type = "pre-release/beta" if is_pre else "stable release"

    system = """\
You are an expert in Home Assistant frontend development and CSS theming. \
You analyze ha-frontend releases for breaking changes, variable renames, \
component refactors, and styling shifts that would affect a third-party \
Home Assistant theme.

The ha-lcars theme works by:
1. Defining CSS custom properties (variables) mapped to LCARS color palette entries
2. Using card-mod / UIX to inject CSS into Home Assistant's shadow DOM tree
3. Targeting specific HA web component element names, CSS classes, and CSS custom properties

Your job: given a release diff and the current ha-lcars theme source, produce a \
severity-organized Markdown report of changes that may require theme updates.

Severity levels:
- **HIGH**: Breaking — a renamed variable, removed element/class/slot, changed shadow DOM \
  structure, or new required layout will visually break the theme without a fix.
- **MEDIUM**: Degraded — something changed that affects appearance (color, spacing, sizing) \
  but may be tolerable or theme-neutral without an update.
- **LOW**: Informational — new features, new variables introduced, or component additions \
  that the theme could optionally style but doesn't need to right now.

Format rules:
- Output valid Markdown only (no code fences around the whole document).
- Start directly with the `## HIGH IMPACT` section (or a note that there are no high-impact items).
- Use `### Component: <name>` sub-headings within each severity section.
- For each item: what changed, what specific ha-lcars CSS rule or variable it affects, \
  and a concrete suggested fix (or "no fix needed" for LOW items).
- If the diff has no styling-relevant changes, say so explicitly in each section.
- Be precise: reference actual CSS property names, variable names, and element/class selectors \
  from both the diff and the LCARS theme source. Do not be vague.
"""

    if pin_mode is not None and core_release is not None:
        # Core just bumped its frontend pin. Frame as "these frontend versions
        # ship together in this Core release" so Claude reasons about the whole
        # range users are about to receive.
        core_tag = core_release["tag_name"]
        core_type = "pre-release" if core_release.get("prerelease") else "stable"
        span_label = "Upcoming Core release" if pin_mode == "pipeline" else "Core release"
        notes_blocks: list[str] = []
        for r in pipeline_releases or []:
            r_body = (r.get("body") or "_(no release notes)_").strip()
            r_type = "pre-release" if r.get("prerelease") else "stable"
            notes_blocks.append(
                f"### {r['tag_name']} — {r['published_at']} ({r_type})\n\n{r_body}"
            )
        notes_section = "\n\n".join(notes_blocks) if notes_blocks else \
            f"### {tag} — {published}\n\n{body}"
        header = (
            f"# {span_label}: Core `{core_tag}` ({core_type})\n"
            f"Frontend pin bumped: `{base_tag or '(none)'}`  →  `{tag}`\n"
            f"Frontend versions included: "
            f"{', '.join(r['tag_name'] for r in (pipeline_releases or [release]))}\n\n"
            f"## Release Notes (each ha-frontend release in this pin bump)\n"
        )
        body_for_prompt = f"{header}\n{notes_section}"
    elif pipeline_releases:
        # Legacy pre-release pipeline framing (no Core context supplied).
        notes_blocks = []
        for r in pipeline_releases:
            r_body = (r.get("body") or "_(no release notes)_").strip()
            notes_blocks.append(
                f"### {r['tag_name']} — {r['published_at']} "
                f"({'pre-release' if r.get('prerelease') else 'stable'})\n\n{r_body}"
            )
        notes_section = "\n\n".join(notes_blocks)
        header = (
            f"# ha-frontend Pre-Release Pipeline Analysis\n"
            f"Last stable: `{base_tag}`  →  Latest beta head: `{tag}`\n"
            f"Releases covered: {len(pipeline_releases)} "
            f"({sum(1 for r in pipeline_releases if r.get('prerelease'))} pre-release(s))\n\n"
            f"## Release Notes (chronological, all releases in window)\n"
        )
        body_for_prompt = f"{header}\n{notes_section}"
    else:
        body_for_prompt = (
            f"# ha-frontend Release: {tag} ({release_type})\n"
            f"Published: {published}\n\n"
            f"## Release Notes\n{body}"
        )

    user = f"""\
{body_for_prompt}

## Changed Files (diff)
{diff_text}

## ha-lcars Theme Source (current)
{lcars_context}

---

Analyze the changes above and produce the severity-organized impact report.
Focus on:
- CSS custom property renames or removals (HA uses `--ha-*`, `--mdc-*`, `--md-*`, etc.)
- Web component element name changes (`hui-*`, `ha-*` elements targeted by card-mod)
- Shadow DOM slot, part, or structure changes that would break `:host`, `::part()`, or slotted selectors
- New layout tokens (padding, sizing, border-radius vars) that the LCARS theme may need to adopt
- Changes to card background, color, or text-color application that would affect card-mod-injected rules

Do NOT report:
- Pure logic/behavior changes with no visual effect
- Translation/string changes
- Test file changes
- Changes to files not present in the diff above
"""

    try:
        message = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=4096,
            system=system,
            messages=[{"role": "user", "content": user}],
        )
    except anthropic.BadRequestError as e:
        if "credit balance" in str(e):
            raise RuntimeError(
                "Anthropic API credits exhausted. Add credits at console.anthropic.com/settings/billing."
            ) from e
        raise

    return message.content[0].text  # type: ignore[index]


# ──────────────────────────────────────────────────────────────────────────────
# Output
# ──────────────────────────────────────────────────────────────────────────────

def build_markdown(
    release: dict,
    analysis: str,
    all_changed_files: list[str],
    pipeline_releases: list[dict] | None = None,
    base_tag: str | None = None,
    core_release: dict | None = None,
    pin_mode: str | None = None,
) -> str:
    tag = release["tag_name"]
    published = release["published_at"]
    is_pre = release.get("prerelease", False)
    release_type = "Pre-release / Beta" if is_pre else "Stable"
    body = (release.get("body") or "").strip()

    now = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

    def _mode_notes_section() -> str:
        # Concatenated ha-frontend release notes for the releases in scope.
        notes_blocks: list[str] = []
        source = pipeline_releases if pipeline_releases is not None else [release]
        for r in source:
            r_body = (r.get("body") or "_No release notes provided._").strip()
            rtype = "pre-release" if r.get("prerelease") else "stable"
            notes_blocks.append(
                f"### {r['tag_name']} — {r['published_at']} ({rtype})\n\n{r_body}"
            )
        return "\n\n".join(notes_blocks) or "_No release notes provided._"

    if pin_mode is not None and core_release is not None:
        # Pin-tracking framing: report is keyed to a Core release that carried
        # the frontend pin bump. Callers write the file with the Core tag as
        # the basename.
        core_tag = core_release["tag_name"]
        core_type = "Pre-release / Beta" if core_release.get("prerelease") else "Stable"
        heading = (
            "# Upcoming HA Core — LCARS Theme Impact Analysis"
            if pin_mode == "pipeline"
            else "# HA Core Release — LCARS Theme Impact Analysis"
        )
        included = pipeline_releases if pipeline_releases is not None else [release]
        included_tags = ", ".join(f"`{r['tag_name']}`" for r in included)
        skipped = [
            r for r in included
            if r["tag_name"] != tag and r["tag_name"] != base_tag
        ]
        skipped_note = (
            f" ({len(skipped)} frontend tag(s) between base and head that Core skipped)"
            if len(included) > 1 else ""
        )
        meta_rows = [
            "| Field | Value |",
            "|-------|-------|",
            f"| Core release | `{core_tag}` |",
            f"| Core type | {core_type} |",
            f"| Core published | {core_release.get('published_at', 'unknown')} |",
            f"| Previous frontend pin | `{base_tag or '(none)'}` |",
            f"| New frontend pin | `{tag}` |",
            f"| Frontend versions included | {included_tags}{skipped_note} |",
            f"| Analyzed | {now} |",
            f"| Changed files | {len(all_changed_files)} |",
        ]
        lines = [
            RELEASE_FILE_PREAMBLE.strip(),
            "",
            heading,
            "",
            *meta_rows,
            "",
            "## Release Notes (each ha-frontend release in this pin bump)",
            "",
            _mode_notes_section(),
        ]
    elif pipeline_releases is not None:
        # Legacy pre-release pipeline framing (used when no Core context).
        title = "# ha-frontend Pre-Release Pipeline — LCARS Theme Impact Analysis"
        meta_rows = [
            "| Field | Value |",
            "|-------|-------|",
            f"| Last stable | `{base_tag}` |",
            f"| Latest beta head | `{tag}` |",
            f"| Releases in window | {len(pipeline_releases)} |",
            f"| Pre-releases | {sum(1 for r in pipeline_releases if r.get('prerelease'))} |",
            f"| Analyzed | {now} |",
            f"| Changed files | {len(all_changed_files)} |",
        ]
        lines = [
            RELEASE_FILE_PREAMBLE.strip(),
            "",
            title,
            "",
            *meta_rows,
            "",
            "## Release Notes (chronological, all releases in window)",
            "",
            _mode_notes_section(),
        ]
    else:
        lines = [
            RELEASE_FILE_PREAMBLE.strip(),
            "",
            f"# ha-frontend {tag} — LCARS Theme Impact Analysis",
            "",
            f"| Field | Value |",
            f"|-------|-------|",
            f"| Release tag | `{tag}` |",
            f"| Type | {release_type} |",
            f"| Published | {published} |",
            f"| Analyzed | {now} |",
            f"| Changed files | {len(all_changed_files)} |",
            "",
            "## Release Notes",
            "",
            body if body else "_No release notes provided._",
        ]

    lines += [
        "",
        "---",
        "",
        analysis,
        "",
        "---",
        "",
        "## All Changed Files",
        "",
        "```",
        *all_changed_files,
        "```",
    ]
    return "\n".join(lines) + "\n"


def write_output(tag: str, content: str) -> Path:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUTPUT_DIR / f"{tag}.md"
    out.write_text(content)
    return out


# ──────────────────────────────────────────────────────────────────────────────
# Release ordering / tag sorting
# ──────────────────────────────────────────────────────────────────────────────

def tag_sort_key(tag: str) -> tuple:
    """Sort HA release tags like '20260527.2' as (20260527, 2)."""
    parts = tag.split(".")
    try:
        return (int(parts[0]), int(parts[1]) if len(parts) > 1 else 0)
    except ValueError:
        return (0, 0)


def find_previous_tag(releases: list[dict], current_tag: str) -> str | None:
    """Return the tag immediately before current_tag in the sorted release list."""
    tags_sorted = sorted([r["tag_name"] for r in releases], key=tag_sort_key)
    try:
        idx = tags_sorted.index(current_tag)
        return tags_sorted[idx - 1] if idx > 0 else None
    except ValueError:
        return None


def find_previous_stable_tag(releases: list[dict], current_tag: str) -> str | None:
    """Return the latest non-prerelease tag strictly before current_tag."""
    by_tag = {r["tag_name"]: r for r in releases}
    sorted_tags = sorted(by_tag.keys(), key=tag_sort_key)
    try:
        idx = sorted_tags.index(current_tag)
    except ValueError:
        return None
    for tag in reversed(sorted_tags[:idx]):
        if not by_tag[tag].get("prerelease", False):
            return tag
    return None


# ──────────────────────────────────────────────────────────────────────────────
# Core processing
# ──────────────────────────────────────────────────────────────────────────────

def process_release(
    release: dict,
    prev_tag: str | None,
    token: str,
    lcars_context: str,
    dry_run: bool = False,
    pipeline_releases: list[dict] | None = None,
    output_basename: str | None = None,
    core_release: dict | None = None,
    pin_mode: str | None = None,
) -> Path:
    """Run the analyzer over a single frontend range and write one report.

    When *core_release* is provided the report is keyed to the Core release
    tag (that tag becomes the filename via *output_basename*, chosen by the
    caller). The *pin_mode* string ("shipped" or "pipeline") controls the
    heading and framing of the report.
    """
    tag = release["tag_name"]
    print(f"\n{'='*60}")
    if core_release is not None:
        print(f"Processing pin bump: {prev_tag or '(none)'} -> {tag}")
        print(f"Carried by Core:     {core_release['tag_name']} "
              f"({'pre-release' if core_release.get('prerelease') else 'stable'})")
        if pipeline_releases:
            print(f"Frontend tags in range: "
                  f"{[r['tag_name'] for r in pipeline_releases]}")
    elif pipeline_releases:
        print(f"Processing pipeline: {prev_tag} -> {tag}")
        print(f"Releases in window: {len(pipeline_releases)}")
    else:
        print(f"Processing: {tag}")
    print(f"Frontend published:  {release['published_at']}")
    print(f"Frontend pre-release: {release.get('prerelease', False)}")

    if prev_tag:
        print(f"Comparing:  {prev_tag}...{tag}")
        compare = get_compare(token, prev_tag, tag)
    else:
        print("No previous tag found — using empty diff (first release)")
        compare = {"files": [], "commits": []}

    diff_text, all_files = format_diff_for_prompt(compare)
    print(f"Diff: {len(compare.get('files', []))} files changed, "
          f"{len([f for f in compare.get('files', []) if is_relevant(f['filename'])])} relevant")

    out_name = output_basename or tag

    if dry_run:
        print("\n[dry-run] Diff text that would be sent to Claude:")
        print(diff_text[:2000])
        print(f"\n[dry-run] LCARS context: {len(lcars_context):,} chars")
        print("[dry-run] Skipping Claude API call and file write.")
        return OUTPUT_DIR / f"{out_name}.md"

    print("Calling Claude Sonnet for analysis...")
    try:
        analysis = analyze_with_claude(
            release, diff_text, lcars_context,
            pipeline_releases=pipeline_releases, base_tag=prev_tag,
            core_release=core_release, pin_mode=pin_mode,
        )
    except RuntimeError as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    content = build_markdown(
        release, analysis, all_files,
        pipeline_releases=pipeline_releases, base_tag=prev_tag,
        core_release=core_release, pin_mode=pin_mode,
    )
    out_path = write_output(out_name, content)
    print(f"Written: {out_path}")
    return out_path


# ──────────────────────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--since", metavar="TAG", help="process all releases after this tag (exclusive)")
    parser.add_argument("--tag", metavar="TAG", help="process a single specific release")
    parser.add_argument("--latest-beta", action="store_true", help="process the latest pre-release/beta only; do not update state file")
    parser.add_argument("--list", action="store_true", help="list recent releases and exit")
    parser.add_argument("--count", type=int, default=50, help="number of releases to fetch from GitHub (default 50)")
    parser.add_argument("--dry-run", action="store_true", help="print diff and prompt context but do not call Claude or write files")
    args = parser.parse_args()

    token = _github_token()

    print("Fetching release list...")
    releases = get_releases(token, per_page=args.count)
    releases_by_tag = {r["tag_name"]: r for r in releases}

    if args.list:
        print(f"\n{'Tag':<20} {'Type':<12} {'Published'}")
        print("-" * 60)
        for r in sorted(releases, key=lambda r: tag_sort_key(r["tag_name"])):
            rtype = "pre-release" if r["prerelease"] else "stable"
            print(f"{r['tag_name']:<20} {rtype:<12} {r['published_at']}")
        return

    lcars_context = load_lcars_context()
    print(f"Loaded LCARS context: {len(lcars_context):,} chars")

    if args.latest_beta:
        # Pipeline framing (pin-driven): compare the frontend pin at the latest
        # Core release of any type (typically a pre-release) against the pin at
        # the latest stable Core release. Emits a single report keyed to the
        # Core pre-release tag. Does not touch the state file (the scheduled
        # run owns that).
        print("Fetching home-assistant/core releases...")
        core_releases = get_core_releases(token, per_page=50)

        head_core, head_pin = resolve_latest_pinning_release(core_releases, prerelease_ok=True)
        base_core, base_pin = resolve_latest_pinning_release(core_releases, prerelease_ok=False)
        if head_core is None or head_pin is None:
            print("No recent Core release pins a frontend version. Nothing to analyze.")
            return
        if base_pin is None:
            print("No stable Core release pins a frontend version — using no base for the diff.")
            base_pin = None
        print(f"Latest Core (any type):  {head_core['tag_name']} pins ha-frontend {head_pin}")
        print(f"Latest stable Core:      "
              f"{base_core['tag_name'] if base_core else '(none)'} "
              f"pins ha-frontend {base_pin}")

        if base_pin and head_pin == base_pin:
            print("Head pin equals stable pin — no upcoming Core changes to report.")
            return

        # Resolve the head release object for release-notes context. Head
        # frontend tag may not be in the top-N cached list; fetch by tag if so.
        head_release = releases_by_tag.get(head_pin)
        if head_release is None:
            try:
                head_release = get_release_by_tag(token, head_pin)
                releases.append(head_release)
                releases_by_tag[head_pin] = head_release
            except Exception as e:
                sys.exit(f"ERROR: could not fetch head frontend release {head_pin}: {e}")

        window = intermediate_frontend_releases(releases, base_pin or "", head_pin)
        # If the API window didn't return enough releases (e.g. base_pin is old),
        # widen to include the head at minimum.
        if not window:
            window = [head_release]
        print(f"Frontend tags in window: {[r['tag_name'] for r in window]}")

        process_release(
            head_release, base_pin, token, lcars_context,
            dry_run=args.dry_run,
            pipeline_releases=window,
            output_basename=f"pipeline-{head_core['tag_name']}",
            core_release=head_core,
            pin_mode="pipeline",
        )
        return

    if args.tag:
        # Process a single specific tag
        if args.tag not in releases_by_tag:
            # Try fetching it directly
            try:
                release = get_release_by_tag(token, args.tag)
                releases.append(release)
                releases_by_tag[args.tag] = release
            except Exception as e:
                sys.exit(f"ERROR: Could not find release {args.tag}: {e}")
        release = releases_by_tag[args.tag]
        prev_tag = find_previous_tag(releases, args.tag)
        process_release(release, prev_tag, token, lcars_context, dry_run=args.dry_run)
        return

    # Auto-mode: pin-driven. On each run, ask what frontend Core currently pins.
    # If it differs from the pin we last analyzed, produce one report covering
    # the range base_pin → head_pin, keyed to the Core release tag that carried
    # the bump. Intermediate frontend tags that Core skipped are included in
    # the release-notes section so nothing goes unrecorded.
    #
    # `--since <frontend_tag>` still works but overrides the pin comparison:
    # it forces the base to that frontend tag. Useful for backfills.
    state = load_state()
    last_pin = args.since or state.get("last_analyzed_pin")

    print("Fetching home-assistant/core releases...")
    core_releases = get_core_releases(token, per_page=50)
    head_core, head_pin = resolve_latest_pinning_release(core_releases, prerelease_ok=True)
    if head_core is None or head_pin is None:
        print("No recent Core release pins a frontend version. Nothing to analyze.")
        return

    print(f"Current pinning Core release: {head_core['tag_name']} "
          f"({'pre-release' if head_core.get('prerelease') else 'stable'}) "
          f"→ ha-frontend {head_pin}")
    print(f"Last analyzed pin:            {last_pin or '(none — first run)'}")

    if last_pin and head_pin == last_pin:
        print("Head pin matches last analyzed pin — nothing new to report.")
        if not args.dry_run:
            state["last_run"] = datetime.now(UTC).isoformat()
            save_state(state)
        return

    if not last_pin:
        # Bootstrap: adopt the current pin without emitting a report. Otherwise
        # first runs would blast the API trying to diff against nothing.
        print("Bootstrapping state — recording current pin without analysis.")
        if not args.dry_run:
            state["last_analyzed_pin"] = head_pin
            state["last_analyzed_core_tag"] = head_core["tag_name"]
            state["last_run"] = datetime.now(UTC).isoformat()
            save_state(state)
        return

    # Resolve the head frontend release object for release-notes context.
    head_release = releases_by_tag.get(head_pin)
    if head_release is None:
        try:
            head_release = get_release_by_tag(token, head_pin)
            releases.append(head_release)
            releases_by_tag[head_pin] = head_release
        except Exception as e:
            sys.exit(f"ERROR: could not fetch head frontend release {head_pin}: {e}")

    # Every ha-frontend release strictly newer than base_pin up to head_pin.
    window = intermediate_frontend_releases(releases, last_pin, head_pin)
    if not window:
        # Guard: if none of the cached releases fall in range (e.g. base pin
        # is older than the top-N cutoff), fall back to the head release only.
        window = [head_release]
    print(f"Frontend tags in this pin bump: {[r['tag_name'] for r in window]}")

    reverted = tag_sort_key(head_pin) < tag_sort_key(last_pin)
    if reverted:
        print("NOTE: pin moved backward — reporting as a pin revert.")

    process_release(
        head_release, last_pin, token, lcars_context,
        dry_run=args.dry_run,
        pipeline_releases=window,
        output_basename=head_core["tag_name"],
        core_release=head_core,
        pin_mode="shipped",
    )

    if not args.dry_run:
        state["last_analyzed_pin"] = head_pin
        state["last_analyzed_core_tag"] = head_core["tag_name"]
        state["last_run"] = datetime.now(UTC).isoformat()
        save_state(state)

    print("\nDone.")


if __name__ == "__main__":
    main()
