#!/usr/bin/env python3
"""
Monitor ha-frontend GitHub releases and analyze their impact on the ha-lcars theme.

Usage:
    python3 py/release_impact.py              # process all new releases since last run
    python3 py/release_impact.py --since 20260101.0  # process releases after this tag
    python3 py/release_impact.py --tag 20260527.2    # process a specific release
    python3 py/release_impact.py --list              # list recent releases without processing

Requires:
    ANTHROPIC_API_KEY environment variable
    GitHub CLI (gh) authenticated, or GITHUB_TOKEN environment variable

State is stored in docs/release-impact/.state.json
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

import requests

REPO_ROOT = Path(__file__).parent.parent
FRONTEND_REPO = "home-assistant/frontend"
OUTPUT_DIR = REPO_ROOT / "docs" / "release-impact"
STATE_FILE = OUTPUT_DIR / ".state.json"
SRC_DIR = REPO_ROOT / "src"

# Files in ha-frontend with high relevance to the LCARS theme
# (CSS vars, card/panel layout, lovelace components, sidebar/header)
RELEVANT_PATH_PREFIXES = (
    "src/panels/lovelace/",
    "src/panels/config/dashboard/",
    "src/components/ha-card",
    "src/components/ha-icon",
    "src/components/ha-chip",
    "src/components/ha-top-app-bar",
    "src/components/ha-sidebar",
    "src/components/ha-navigation-list",
    "src/components/ha-entity",
    "src/components/ha-state",
    "src/components/ha-button",
    "src/components/ha-slider",
    "src/layouts/",
    "src/resources/",
    "src/styles/",
    "hassio/src/",
)
# Skip files that are very unlikely to touch styling
SKIP_SUFFIXES = (
    ".json",
    ".md",
    "test.ts",
    ".spec.ts",
    "_test.ts",
    "translations/",
    "localize/",
)

MAX_PATCH_CHARS = 800     # per file
MAX_DIFF_FILES = 60       # total files to send to Claude

RELEASE_FILE_PREAMBLE = """\
<!-- AUTO-GENERATED by py/release_impact.py — DO NOT EDIT MANUALLY -->
<!--
  This file was generated by the ha-frontend release impact analyzer.
  It summarizes changes in an ha-frontend release that may affect the ha-lcars theme.

  DEVELOPER INSTRUCTIONS:
    1. Review each item below. Items in the HIGH IMPACT section require attention first.
    2. For each issue you resolve (variable renamed, selector changed, etc.), mark it done
       by adding a ✅ to the start of that bullet point.
    3. When ALL items are resolved, DELETE THIS FILE from the repository.

  Do not merge this file into main — it is a working document only.
-->
"""


# ──────────────────────────────────────────────────────────────────────────────
# GitHub helpers
# ──────────────────────────────────────────────────────────────────────────────

def _github_token() -> str:
    tok = os.environ.get("GITHUB_TOKEN", "")
    if not tok:
        try:
            tok = subprocess.check_output(["gh", "auth", "token"], text=True).strip()
        except Exception:
            pass
    if not tok:
        sys.exit("ERROR: No GitHub token found. Set GITHUB_TOKEN or authenticate via `gh auth login`.")
    return tok


def gh_get(path: str, token: str, params: dict | None = None) -> dict | list:
    url = f"https://api.github.com/{path.lstrip('/')}"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    resp = requests.get(url, headers=headers, params=params, timeout=30)
    resp.raise_for_status()
    return resp.json()


def get_releases(token: str, per_page: int = 50) -> list[dict]:
    return gh_get(f"repos/{FRONTEND_REPO}/releases", token, params={"per_page": per_page})  # type: ignore[return-value]


def get_compare(token: str, base: str, head: str) -> dict:
    return gh_get(f"repos/{FRONTEND_REPO}/compare/{base}...{head}", token)  # type: ignore[return-value]


def get_release_by_tag(token: str, tag: str) -> dict:
    return gh_get(f"repos/{FRONTEND_REPO}/releases/tags/{tag}", token)  # type: ignore[return-value]


# ──────────────────────────────────────────────────────────────────────────────
# State management
# ──────────────────────────────────────────────────────────────────────────────

def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {}


def save_state(state: dict) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2))


# ──────────────────────────────────────────────────────────────────────────────
# LCARS theme context
# ──────────────────────────────────────────────────────────────────────────────

def load_lcars_context() -> str:
    """Return a condensed text summary of the LCARS theme for Claude context."""
    parts: list[str] = []

    defaults_path = SRC_DIR / "defaults.yaml"
    if defaults_path.exists():
        parts.append("=== ha-lcars/src/defaults.yaml (CSS variable definitions) ===")
        parts.append(defaults_path.read_text())

    preamble_path = SRC_DIR / "preamble.yaml"
    if preamble_path.exists():
        parts.append("=== ha-lcars/src/preamble.yaml (card-mod/UIX CSS injection rules) ===")
        parts.append(preamble_path.read_text())

    return "\n\n".join(parts)


# ──────────────────────────────────────────────────────────────────────────────
# Diff filtering
# ──────────────────────────────────────────────────────────────────────────────

def is_relevant(filename: str) -> bool:
    for suffix in SKIP_SUFFIXES:
        if suffix in filename:
            return False
    for prefix in RELEVANT_PATH_PREFIXES:
        if filename.startswith(prefix):
            return True
    # Also catch any file that explicitly touches CSS custom properties
    return False


def format_diff_for_prompt(compare: dict) -> tuple[str, list[str]]:
    """Return (formatted diff text, list of all changed filenames)."""
    all_files = compare.get("files", [])
    all_names = [f["filename"] for f in all_files]

    relevant = [f for f in all_files if is_relevant(f["filename"])]
    other = [f for f in all_files if not is_relevant(f["filename"])]

    lines: list[str] = []

    lines.append(f"Total files changed: {len(all_files)}")
    lines.append(f"Relevant to LCARS styling (included below): {len(relevant)}")
    lines.append(f"Other files (names only): {len(other)}")
    if other:
        lines.append("  " + ", ".join(f["filename"] for f in other[:40]))
        if len(other) > 40:
            lines.append(f"  ... and {len(other) - 40} more")
    lines.append("")

    included = relevant[:MAX_DIFF_FILES]
    for f in included:
        lines.append(f"--- {f['filename']}  (+{f['additions']} -{f['deletions']}) ---")
        patch = f.get("patch", "")
        if patch:
            if len(patch) > MAX_PATCH_CHARS:
                patch = patch[:MAX_PATCH_CHARS] + f"\n... [truncated, {len(patch) - MAX_PATCH_CHARS} more chars]"
            lines.append(patch)
        else:
            lines.append("[binary or empty diff]")
        lines.append("")

    return "\n".join(lines), all_names


# ──────────────────────────────────────────────────────────────────────────────
# Claude analysis
# ──────────────────────────────────────────────────────────────────────────────

def analyze_with_claude(
    release: dict,
    diff_text: str,
    lcars_context: str,
) -> str:
    """Call Claude Sonnet and return the raw markdown analysis."""
    import anthropic

    client = anthropic.Anthropic()

    tag = release["tag_name"]
    published = release["published_at"]
    body = release.get("body") or "(no release notes)"
    is_pre = release.get("prerelease", False)
    release_type = "pre-release/beta" if is_pre else "stable release"

    system = """\
You are an expert in Home Assistant frontend development and CSS theming. \
You analyze ha-frontend releases for breaking changes, variable renames, \
component refactors, and styling shifts that would affect a third-party \
Home Assistant theme.

The ha-lcars theme works by:
1. Defining CSS custom properties (variables) mapped to LCARS color palette entries
2. Using card-mod / UIX to inject CSS into Home Assistant's shadow DOM tree
3. Targeting specific HA web component element names, CSS classes, and CSS custom properties

Your job: given a release diff and the current ha-lcars theme source, produce a \
severity-organized Markdown report of changes that may require theme updates.

Severity levels:
- **HIGH**: Breaking — a renamed variable, removed element/class/slot, changed shadow DOM \
  structure, or new required layout will visually break the theme without a fix.
- **MEDIUM**: Degraded — something changed that affects appearance (color, spacing, sizing) \
  but may be tolerable or theme-neutral without an update.
- **LOW**: Informational — new features, new variables introduced, or component additions \
  that the theme could optionally style but doesn't need to right now.

Format rules:
- Output valid Markdown only (no code fences around the whole document).
- Start directly with the `## HIGH IMPACT` section (or a note that there are no high-impact items).
- Use `### Component: <name>` sub-headings within each severity section.
- For each item: what changed, what specific ha-lcars CSS rule or variable it affects, \
  and a concrete suggested fix (or "no fix needed" for LOW items).
- If the diff has no styling-relevant changes, say so explicitly in each section.
- Be precise: reference actual CSS property names, variable names, and element/class selectors \
  from both the diff and the LCARS theme source. Do not be vague.
"""

    user = f"""\
# ha-frontend Release: {tag} ({release_type})
Published: {published}

## Release Notes
{body}

## Changed Files (diff)
{diff_text}

## ha-lcars Theme Source (current)
{lcars_context}

---

Analyze the changes above and produce the severity-organized impact report.
Focus on:
- CSS custom property renames or removals (HA uses `--ha-*`, `--mdc-*`, `--md-*`, etc.)
- Web component element name changes (`hui-*`, `ha-*` elements targeted by card-mod)
- Shadow DOM slot, part, or structure changes that would break `:host`, `::part()`, or slotted selectors
- New layout tokens (padding, sizing, border-radius vars) that the LCARS theme may need to adopt
- Changes to card background, color, or text-color application that would affect card-mod-injected rules

Do NOT report:
- Pure logic/behavior changes with no visual effect
- Translation/string changes
- Test file changes
- Changes to files not present in the diff above
"""

    try:
        message = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=4096,
            system=system,
            messages=[{"role": "user", "content": user}],
        )
    except anthropic.BadRequestError as e:
        if "credit balance" in str(e):
            raise RuntimeError(
                "Anthropic API credits exhausted. Add credits at console.anthropic.com/settings/billing."
            ) from e
        raise

    return message.content[0].text  # type: ignore[index]


# ──────────────────────────────────────────────────────────────────────────────
# Output
# ──────────────────────────────────────────────────────────────────────────────

def build_markdown(release: dict, analysis: str, all_changed_files: list[str]) -> str:
    tag = release["tag_name"]
    published = release["published_at"]
    is_pre = release.get("prerelease", False)
    release_type = "Pre-release / Beta" if is_pre else "Stable"
    body = (release.get("body") or "").strip()

    now = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        RELEASE_FILE_PREAMBLE.strip(),
        "",
        f"# ha-frontend {tag} — LCARS Theme Impact Analysis",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Release tag | `{tag}` |",
        f"| Type | {release_type} |",
        f"| Published | {published} |",
        f"| Analyzed | {now} |",
        f"| Changed files | {len(all_changed_files)} |",
        "",
        "## Release Notes",
        "",
        body if body else "_No release notes provided._",
        "",
        "---",
        "",
        analysis,
        "",
        "---",
        "",
        "## All Changed Files",
        "",
        "```",
        *all_changed_files,
        "```",
    ]
    return "\n".join(lines) + "\n"


def write_output(tag: str, content: str) -> Path:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUTPUT_DIR / f"{tag}.md"
    out.write_text(content)
    return out


# ──────────────────────────────────────────────────────────────────────────────
# Release ordering / tag sorting
# ──────────────────────────────────────────────────────────────────────────────

def tag_sort_key(tag: str) -> tuple:
    """Sort HA release tags like '20260527.2' as (20260527, 2)."""
    parts = tag.split(".")
    try:
        return (int(parts[0]), int(parts[1]) if len(parts) > 1 else 0)
    except ValueError:
        return (0, 0)


def find_previous_tag(releases: list[dict], current_tag: str) -> str | None:
    """Return the tag immediately before current_tag in the sorted release list."""
    tags_sorted = sorted([r["tag_name"] for r in releases], key=tag_sort_key)
    try:
        idx = tags_sorted.index(current_tag)
        return tags_sorted[idx - 1] if idx > 0 else None
    except ValueError:
        return None


# ──────────────────────────────────────────────────────────────────────────────
# Core processing
# ──────────────────────────────────────────────────────────────────────────────

def process_release(release: dict, prev_tag: str | None, token: str, lcars_context: str, dry_run: bool = False) -> Path:
    tag = release["tag_name"]
    print(f"\n{'='*60}")
    print(f"Processing: {tag}")
    print(f"Published:  {release['published_at']}")
    print(f"Pre-release: {release.get('prerelease', False)}")

    if prev_tag:
        print(f"Comparing:  {prev_tag}...{tag}")
        compare = get_compare(token, prev_tag, tag)
    else:
        print("No previous tag found — using empty diff (first release)")
        compare = {"files": [], "commits": []}

    diff_text, all_files = format_diff_for_prompt(compare)
    print(f"Diff: {len(compare.get('files', []))} files changed, {len([f for f in compare.get('files', []) if is_relevant(f['filename'])])} relevant")

    if dry_run:
        print("\n[dry-run] Diff text that would be sent to Claude:")
        print(diff_text[:2000])
        print(f"\n[dry-run] LCARS context: {len(lcars_context):,} chars")
        print("[dry-run] Skipping Claude API call and file write.")
        return OUTPUT_DIR / f"{tag}.md"

    print("Calling Claude Sonnet for analysis...")
    try:
        analysis = analyze_with_claude(release, diff_text, lcars_context)
    except RuntimeError as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    content = build_markdown(release, analysis, all_files)
    out_path = write_output(tag, content)
    print(f"Written: {out_path}")
    return out_path


# ──────────────────────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--since", metavar="TAG", help="process all releases after this tag (exclusive)")
    parser.add_argument("--tag", metavar="TAG", help="process a single specific release")
    parser.add_argument("--list", action="store_true", help="list recent releases and exit")
    parser.add_argument("--count", type=int, default=50, help="number of releases to fetch from GitHub (default 50)")
    parser.add_argument("--dry-run", action="store_true", help="print diff and prompt context but do not call Claude or write files")
    args = parser.parse_args()

    token = _github_token()

    print("Fetching release list...")
    releases = get_releases(token, per_page=args.count)
    releases_by_tag = {r["tag_name"]: r for r in releases}

    if args.list:
        print(f"\n{'Tag':<20} {'Type':<12} {'Published'}")
        print("-" * 60)
        for r in sorted(releases, key=lambda r: tag_sort_key(r["tag_name"])):
            rtype = "pre-release" if r["prerelease"] else "stable"
            print(f"{r['tag_name']:<20} {rtype:<12} {r['published_at']}")
        return

    lcars_context = load_lcars_context()
    print(f"Loaded LCARS context: {len(lcars_context):,} chars")

    if args.tag:
        # Process a single specific tag
        if args.tag not in releases_by_tag:
            # Try fetching it directly
            try:
                release = get_release_by_tag(token, args.tag)
                releases.append(release)
                releases_by_tag[args.tag] = release
            except Exception as e:
                sys.exit(f"ERROR: Could not find release {args.tag}: {e}")
        release = releases_by_tag[args.tag]
        prev_tag = find_previous_tag(releases, args.tag)
        process_release(release, prev_tag, token, lcars_context, dry_run=args.dry_run)
        return

    # Auto-mode: process all new releases since last run (or --since)
    state = load_state()
    last_tag = args.since or state.get("last_processed_tag")

    tags_sorted = sorted(releases_by_tag.keys(), key=tag_sort_key)

    if last_tag:
        try:
            cutoff_idx = tags_sorted.index(last_tag)
            new_tags = tags_sorted[cutoff_idx + 1:]
        except ValueError:
            print(f"Warning: last_tag '{last_tag}' not found in recent releases. Processing all.")
            new_tags = tags_sorted
    else:
        # First run — only process the most recent release to avoid blasting the API
        print("No previous state found. Processing only the latest release.")
        print("To process more, use --since <tag> or --tag <tag>.")
        new_tags = tags_sorted[-1:] if tags_sorted else []

    if not new_tags:
        print("No new releases to process.")
        if tags_sorted:
            print(f"Last seen tag: {last_tag}")
            print(f"Latest available: {tags_sorted[-1]}")
        return

    print(f"\nNew releases to process: {new_tags}")

    for tag in new_tags:
        release = releases_by_tag[tag]
        prev_tag = find_previous_tag(releases, tag)
        process_release(release, prev_tag, token, lcars_context, dry_run=args.dry_run)
        if not args.dry_run:
            # Update state after each success so a failure mid-run doesn't reprocess
            state["last_processed_tag"] = tag
            state["last_run"] = datetime.now(UTC).isoformat()
            save_state(state)

    print(f"\nDone. Processed {len(new_tags)} release(s).")


if __name__ == "__main__":
    main()
