name: LCARS Default

lcars-ui-primary: var(--lcars-almond-creme)
lcars-ui-secondary: var(--lcars-african-violet)
lcars-ui-tertiary: var(--lcars-red)
lcars-ui-quaternary: var(--lcars-gray)
lcars-ui-quaternary-text: var(--lcars-text-dark)

lcars-ui-config-button: var(--lcars-ui-secondary)

lcars-card-top-color: var(--lcars-bluey)
lcars-card-mid-color: var(--lcars-red)
lcars-card-button-color: var(--lcars-red)
lcars-card-bottom-color: var(--lcars-gray)
lcars-settings-card-color: "#727295"

lcars-card-top-text: var(--lcars-text-dark)
lcars-card-mid-text: var(--lcars-text-dark)
lcars-card-button-text: var(--lcars-text-dark)
lcars-card-bottom-text: var(--lcars-text-light)

success-color: var(--lcars-green)
warning-color: var(--lcars-sunflower)
error-color: var(--lcars-dark-red)

modes:
  light:
    lcars-ui-quaternary-text: var(--lcars-text-light)
  dark:
    lcars-ui-quaternary-text: var(--lcars-text-dark)
