name: Build and Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-theme:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
         persist-credentials: true
      - name: Run Generation Script
        run: python py/generate_themes.py
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: generate theme file"
          file_pattern: "themes/lcars.yaml"

  validate-hacs:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: "actions/checkout@v6"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "theme"

  validate-hassfest:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
        - uses: "actions/checkout@v6"
        - uses: "home-assistant/actions/hassfest@master"
  
  flatten-css:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
         persist-credentials: true
      - name: Run Flatten Script
        run: python py/flatten_ha_theme_css.py -o "themes/lcars_flat.yaml" "themes/lcars.yaml" 
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: flatten nested theme css"
          file_pattern: "themes/lcars_flat.yaml"
