name: Build and Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
         persist-credentials: true
      - name: Run Generation Script
        run: python py/generate_themes.py
      - name: Run Flatten Script
        run: python py/flatten_ha_theme_css.py -o "themes/lcars_flat.yaml" "themes/lcars.yaml" 
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: generate theme files"
          file_pattern: "themes/lcars.yaml themes/lcars_flat.yaml"
      - name: HACS Validation
        uses: "hacs/action@main"
        with:
          category: "theme"
      - name: Hassfest Validation
        uses: "home-assistant/actions/hassfest@master"
